###################################################
## Global Config                                  #
###################################################
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Prometheus_Monitor'

##################################################
# Node_Exporter with Service Discovery           #
##################################################
scrape_configs:
  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
        - conf.d/node.yml
        refresh_interval: 5m
    relabel_configs:
    - source_labels: ["job"]
      regex: '(.*)'
      replacement: $1
      action: replace
      target_label: "project"
##################################################
# WMI_Exporter with Service Discovery           #
##################################################
  - job_name: 'wmi_exporter'
    file_sd_configs:
      - files:
        - conf.d/wmi.yml
        refresh_interval: 5m
    relabel_configs:
    - source_labels: ["job"]
      regex: '(.*)'
      replacement: $1
      action: replace
      target_label: "project"
##################################################
# Blackbox_Exporter with Service Discovery       #
##################################################
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: 
        - conf.d/blackbox.yml
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__address__]
      regex: '(.*)'
      replacement: $1
      action: replace
      target_label: "target"
    - target_label: __address__
      replacement: 10.10.1.12:9115
##################################################
# cAdvisor with Service Discovery                #
##################################################
  - job_name: 'cAdvisor'
    file_sd_configs:
      - files:
        - conf.d/cadvisor.yml
        refresh_interval: 5m
    relabel_configs:
    - source_labels: ["job"]
      regex: '(.*)'
      replacement: $1
      action: replace
      target_label: "project"