version: '3.2'

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    container_name: prom
    volumes:
      - "$PWD/prom/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "$PWD/prom/prometheus/:/prometheus/"
      - "$PWD/prom/conf.d/:/etc/prometheus/conf.d/"
    restart: always
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=90d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.max-block-duration=7d'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:9.1.6
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
      - $PWD/grafana/etc:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=peter10216
      - GF_SECURITY_ADMIN_PASSWORD=2ddiruxl
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    restart: always

  renderer:
    image: grafana/grafana-image-renderer:3.6.1
    container_name: renderer
    ports:
      - "8081:8081"
    volumes:
      - $PWD/grafana/renderer/config.json:/usr/src/app/config.json
    restart: always

  blackbox:
    image: prom/blackbox-exporter:v0.22.0
    container_name: blackbox
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - $PWD/blackbox/:/etc/blackbox/
    command: --config.file=/etc/blackbox/blackbox.yml

  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    restart: always
    ports:
     - 9080:8080
    volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro