{
 "title": "Home Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode='idle'}[1m])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load average (per core)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(node_load1) / count by (instance)(node_cpu_seconds_total{mode='idle'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk io",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "(-) Write / Read (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_R"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_W"
    }
   ]
  },
  {
   "title": "Disk Space Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * (node_filesystem_avail_bytes{mountpoint=\"/\",fstype=\"xfs\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Throughtput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "(-) Write / Read (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_R"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_W"
    }
   ]
  },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Time Wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_sockstat_TCP_tw", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network Throughtput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "(-) Download / Upload (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_D"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "{{instance}}[{{device}}]_U"
    }
   ]
  }
 ]
}