[[servers]]
host = "rich.net"
port = 3268
use_ssl = false
start_tls = false
ssl_skip_verify = false


bind_dn = "grafana@rich.net"
bind_password = 'Ccna@123'
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["OU=Admin,DC=RICH,DC=NET"]
group_search_base_dns = ["OU=Admin,DC=RICH,DC=NET"]


[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"


[[servers.group_mappings]]
group_dn = "CN=admin,OU=Admin-Group,DC=RICH,DC=NET"
org_role = "Admin"


[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"