[[servers]]
host = "rinrin.net"
port = 3268
use_ssl = false
start_tls = false
ssl_skip_verify = false


bind_dn = "grafana@rinrin.net"
bind_password = "rinriN@123"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["OU=AdminUser,DC=rinrin,DC=net"]
group_search_base_dns = ["OU=AdminUser,DC=rinrin,DC=net"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"


[[servers.group_mappings]]
group_dn = "CN=AdminGroup,OU=Group,DC=rinrin,DC=net"
org_role = "Admin"


[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
